# Generated by Django 2.1.5 on 2019-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('stars', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_date', models.DateField()),
                ('days_count', models.PositiveSmallIntegerField()),
                ('departure_place', models.CharField(max_length=255)),
                ('country', models.ManyToManyField(to='tours.Country')),
                ('hotel', models.ManyToManyField(to='tours.Hotel')),
            ],
        ),
    ]
