# Generated by Django 2.1.5 on 2019-05-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20190516_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tours.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='tours.Hotel'),
        ),
    ]
