# Generated by Django 2.1.5 on 2019-05-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20190517_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tours.Place'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tour',
            name='place',
        ),
        migrations.AddField(
            model_name='tour',
            name='place',
            field=models.ManyToManyField(blank=True, to='tours.Place'),
        ),
    ]
