# Generated by Django 2.2.1 on 2019-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20190520_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
